import json

metadata = {
    "001.png": {"title": "The Leviathan's Twilight Breach", "tags": ["cosmic horror", "leviathan", "ocean ambient", "lovecraftian"]},
    "002.png": {"title": "The Lighthouse That Saw Too Much", "tags": ["cosmic horror", "lighthouse", "fog ambience", "lovecraftian"]},
    "003.png": {"title": "Adrift in the Glass Void", "tags": ["cosmic horror", "ocean ambient", "dark ocean", "lovecraftian"]},
    "004.png": {"title": "The Harbor Shadow of R'lyeh", "tags": ["cthulhu", "cosmic horror", "harbor fog", "lovecraftian"]},
    "005.png": {"title": "The Sunken Spires of the Abyss", "tags": ["drowned cathedral", "cosmic horror", "underwater ambient", "lovecraftian"]},
    "006.png": {"title": "The Eye Beneath Rome", "tags": ["submerged ruins", "cosmic horror", "ancient mystery", "lovecraftian"]},
    "007.png": {"title": "The Wave That Remembered", "tags": ["cosmic horror", "tsunami", "coastal village", "lovecraftian"]},
    "008.png": {"title": "Non-Euclidean Ice Secrets", "tags": ["antarctic", "cosmic horror", "ice shelf", "lovecraftian"]},
    "009.png": {"title": "The Shore of Three Setting Suns", "tags": ["alien sky", "cosmic horror", "basalt coast", "lovecraftian"]},
    "010.png": {"title": "The Violet Pulse of the Drift", "tags": ["shipwreck", "cosmic horror", "violet light", "lovecraftian"]},
    "011.png": {"title": "The Abyssal Ribcage Glow", "tags": ["whale fall", "cosmic horror", "deep sea", "lovecraftian"]},
    "012.png": {"title": "Standing on the Midnight Surface", "tags": ["liminal", "cosmic horror", "still water", "lovecraftian"]},
    "013.png": {"title": "The Icebound Ghost of HMS Erebus", "tags": ["arctic horror", "ghost ship", "pack ice", "lovecraftian"]},
    "014.png": {"title": "The Fractal Sailor", "tags": ["ice cathedral", "cosmic horror", "fractal", "lovecraftian"]},
    "015.png": {"title": "The Pale Horizon Witness", "tags": ["arctic horror", "liminal space", "four moons", "lovecraftian"]},
    "016.png": {"title": "The Glacier's Pulsing Vein", "tags": ["prehistoric horror", "glacier", "mammoth", "lovecraftian"]},
    "017.png": {"title": "Crystalline Caverns of the Deep", "tags": ["subglacial", "cosmic horror", "crystals", "lovecraftian"]},
    "018.png": {"title": "The Eye in the Aurora", "tags": ["arctic horror", "aurora", "cosmic eye", "lovecraftian"]},
    "019.png": {"title": "The Icebreaker's Frozen Wave", "tags": ["nuclear icebreaker", "arctic horror", "frozen time", "lovecraftian"]},
    "020.png": {"title": "The Monolith of the Tundra", "tags": ["monolith", "cosmic horror", "tundra", "lovecraftian"]},
    "021.png": {"title": "Cyclopean Carvings of the Berg", "tags": ["iceberg", "cosmic horror", "ancient carvings", "lovecraftian"]},
    "022.png": {"title": "The Glowing Eyes of the Pack", "tags": ["arctic horror", "husky", "frozen", "lovecraftian"]},
    "023.png": {"title": "The 3AM Laundromat Figure", "tags": ["liminal space", "urban horror", "laundromat", "cosmic horror"]},
    "024.png": {"title": "The Garage Elongated Shadow", "tags": ["liminal space", "urban horror", "parking garage", "cosmic horror"]},
    "025.png": {"title": "The Dark House in the Cul-de-sac", "tags": ["suburban horror", "liminal space", "dark house", "cosmic horror"]},
    "026.png": {"title": "The Diner That Swallowed the Fog", "tags": ["liminal space", "diner", "fog ambience", "cosmic horror"]},
    "027.png": {"title": "The Stairwell That Never Ends", "tags": ["liminal space", "stairwell", "infinite", "cosmic horror"]},
    "028.png": {"title": "The Wrong Reflection in the Pool", "tags": ["suburban horror", "swimming pool", "reflection", "cosmic horror"]},
    "029.png": {"title": "The Midnight Bus Passenger", "tags": ["urban horror", "liminal space", "empty bus", "cosmic horror"]},
    "030.png": {"title": "The Hallway of Infinite Doors", "tags": ["liminal space", "hallway", "backrooms", "cosmic horror"]},
    "031.png": {"title": "The Floating Item in the Mall", "tags": ["liminal space", "dead mall", "vending machine", "cosmic horror"]},
    "032.png": {"title": "The Wrong Scarecrows", "tags": ["rural horror", "scarecrow", "night", "cosmic horror"]},
    "033.png": {"title": "The Shape in the Condensation", "tags": ["urban horror", "bathroom mirror", "mist", "cosmic horror"]},
    "034.png": {"title": "The 2AM Office Monitor", "tags": ["liminal space", "office horror", "empty building", "cosmic horror"]},
    "035.png": {"title": "The Station Over the New Planet", "tags": ["space horror", "abandoned station", "scifi ambient", "cosmic horror"]},
    "036.png": {"title": "The Eye That Opens in the Void", "tags": ["space horror", "astronaut", "nebula", "cosmic horror"]},
    "037.png": {"title": "The Day Earth Vanished", "tags": ["space horror", "moon base", "missing earth", "cosmic horror"]},
    "038.png": {"title": "The Half-Eaten Dyson Swarm", "tags": ["space horror", "dyson swarm", "scifi ambient", "cosmic horror"]},
    "039.png": {"title": "The Black Monument of Mars", "tags": ["space horror", "mars", "monolith", "cosmic horror"]},
    "040.png": {"title": "The Crystalline Cosmonaut", "tags": ["space horror", "cosmonaut", "crystals", "cosmic horror"]},
    "041.png": {"title": "The Dish That Found the Dark", "tags": ["space horror", "telescope", "dark star", "cosmic horror"]},
    "042.png": {"title": "The Face in the Nebula", "tags": ["space horror", "nebula", "sleeping face", "cosmic horror"]},
    "043.png": {"title": "Caught in the Light-Bend", "tags": ["space horror", "solar sail", "anomaly", "cosmic horror"]},
    "044.png": {"title": "The Shattered Shards of Saturn", "tags": ["space horror", "saturn rings", "broken", "cosmic horror"]},
    "045.png": {"title": "The ISS Viewport Secret", "tags": ["space horror", "iss", "tentacles", "cosmic horror"]},
    "046.png": {"title": "The Spiral Staircase of the Abyss", "tags": ["space horror", "black hole", "infinite", "cosmic horror"]},
    "047.png": {"title": "Eyes in the Cypress Swamp", "tags": ["swamp horror", "rowboat", "dark water", "cosmic horror"]},
    "048.png": {"title": "The Forest That Tilted", "tags": ["forest horror", "pine forest", "anomaly", "cosmic horror"]},
    "049.png": {"title": "The Bog Body of the Stones", "tags": ["swamp horror", "bog body", "standing stones", "cosmic horror"]},
    "050.png": {"title": "The Redwood Trunk Window", "tags": ["forest horror", "redwoods", "secret window", "cosmic horror"]},
    "051.png": {"title": "The Black Puddle in the Snow", "tags": ["forest horror", "clearing", "anomaly", "cosmic horror"]},
    "052.png": {"title": "The Chime of the Deer Skull", "tags": ["forest horror", "totem", "bones", "cosmic horror"]},
    "053.png": {"title": "The Pulsing Moss Megalith", "tags": ["forest horror", "megalith", "ancient", "cosmic horror"]},
    "054.png": {"title": "The Hand in the Lake Mist", "tags": ["forest horror", "mountain lake", "mist hand", "cosmic horror"]},
    "055.png": {"title": "The Crashed Cosmic Egg", "tags": ["forest horror", "heath", "alien artifact", "cosmic horror"]},
    "056.png": {"title": "The Cabin of Identical Figures", "tags": ["forest horror", "hunting cabin", "doppelganger", "cosmic horror"]},
    "057.png": {"title": "The Basalt Trench City", "tags": ["architecture horror", "cyclopean", "sunken city", "cosmic horror"]},
    "058.png": {"title": "The Escher Cathedral Candle", "tags": ["architecture horror", "infinite stairs", "cathedral", "cosmic horror"]},
    "059.png": {"title": "The Desert Storm Watchtower", "tags": ["architecture horror", "desert", "storm tower", "cosmic horror"]},
    "060.png": {"title": "The Ziggurat's Violet Mist", "tags": ["architecture horror", "ziggurat", "ancient ruins", "cosmic horror"]},
    "061.png": {"title": "Soviet Bunker Coordinates", "tags": ["architecture horror", "soviet", "bunker", "cosmic horror"]},
    "062.png": {"title": "The Brutalist Tower of Time", "tags": ["architecture horror", "brutalist", "time anomaly", "cosmic horror"]},
    "063.png": {"title": "The Forbidden Nave of the Basilica", "tags": ["architecture horror", "underwater", "basilica", "cosmic horror"]},
    "064.png": {"title": "The Luminous Aqueduct", "tags": ["architecture horror", "ruins", "glowing fluid", "cosmic horror"]},
    "065.png": {"title": "The Void in the Mausoleum", "tags": ["architecture horror", "mausoleum", "cliff side", "cosmic horror"]},
    "066.png": {"title": "The House That Cast No Shadow", "tags": ["architecture horror", "mojave", "modernist", "cosmic horror"]},
    "067.png": {"title": "Mammoths Under the Aurora", "tags": ["prehistoric cozy", "mammoth", "peaceful", "winter ambient"]},
    "068.png": {"title": "Dinosaur Lake Golden Hour", "tags": ["prehistoric cozy", "dinosaurs", "sunset lake", "peaceful ambient"]},
    "069.png": {"title": "The Cretaceous River Dawn", "tags": ["prehistoric cozy", "pterosaurs", "river mouth", "peaceful ambient"]},
    "070.png": {"title": "The Still Tar Pit Twilight", "tags": ["prehistoric cozy", "tar pit", "twilight", "peaceful ambient"]},
    "071.png": {"title": "The Jurassic Treehouse Lanterns", "tags": ["prehistoric cozy", "treehouse", "village", "peaceful ambient"]},
    "072.png": {"title": "Sauropods in the Moonlight", "tags": ["prehistoric cozy", "dinosaurs", "full moon", "peaceful ambient"]},
    "073.png": {"title": "The Coastal Bluff Fire", "tags": ["prehistoric cozy", "mesolithic", "campfire", "peaceful ambient"]},
    "074.png": {"title": "The Alpine Plesiosaur", "tags": ["prehistoric cozy", "plesiosaur", "mountain lake", "peaceful ambient"]},
    "075.png": {"title": "Sunrise Over the Inland Sea", "tags": ["prehistoric cozy", "archaeopteryx", "sunrise", "peaceful ambient"]},
    "076.png": {"title": "Drifting Through the Ancient Swamp", "tags": ["prehistoric cozy", "canoe", "swamp", "peaceful ambient"]},
    "077.png": {"title": "The Fire on the Cave Wall", "tags": ["prehistoric cozy", "cave painters", "mammoth", "peaceful ambient"]},
    "078.png": {"title": "Salt Flat Silhouettes", "tags": ["prehistoric cozy", "megafauna", "salt flats", "peaceful ambient"]},
    "079.png": {"title": "The Lunar Greenhouse Bloom", "tags": ["future nostalgic", "moon base", "greenhouse", "cozy scifi"]},
    "080.png": {"title": "The Golden Plaza Reclamation", "tags": ["future nostalgic", "solarpunk", "overgrown", "cozy scifi"]},
    "081.png": {"title": "Sunset in the Arcology", "tags": ["future nostalgic", "monorail", "arcology", "cozy scifi"]},
    "082.png": {"title": "The Coral Space Elevator", "tags": ["future nostalgic", "space elevator", "overgrown", "cozy scifi"]},
    "083.png": {"title": "Floating Ships of the Cloud Sea", "tags": ["future nostalgic", "cloud city", "ships", "cozy scifi"]},
    "084.png": {"title": "The Last Light in the Biodome", "tags": ["future nostalgic", "biodome", "desert dusk", "cozy scifi"]},
    "085.png": {"title": "Midnight Snow in Future Bucharest", "tags": ["future nostalgic", "maglev", "bucharest", "cozy scifi"]},
    "086.png": {"title": "The Mars Colony Library", "tags": ["future nostalgic", "mars base", "library", "cozy scifi"]},
    "087.png": {"title": "Turtles of the Underwater Station", "tags": ["future nostalgic", "underwater station", "ocean", "cozy scifi"]},
    "088.png": {"title": "Drifting Orbital Ring Sunset", "tags": ["future nostalgic", "orbital ring", "sunset", "cozy scifi"]},
    "089.png": {"title": "Icy Moon Hot Spring Resort", "tags": ["future nostalgic", "icy moon", "hot spring", "cozy scifi"]},
    "090.png": {"title": "Rooftop Garden Drone Fireflies", "tags": ["future nostalgic", "rooftop garden", "cyberpunk", "cozy scifi"]},
    "091.png": {"title": "The Infinite Subway Platform", "tags": ["dream liminal", "subway", "symmetry", "dreamcore"]},
    "092.png": {"title": "The Hotel of Repeating Patterns", "tags": ["dream liminal", "hotel", "infinite", "dreamcore"]},
    "093.png": {"title": "The 4AM Airport Silhouette", "tags": ["dream liminal", "airport", "empty", "dreamcore"]},
    "094.png": {"title": "The Indoor Pool Sky", "tags": ["dream liminal", "indoor pool", "reflection", "dreamcore"]},
    "095.png": {"title": "The Library of Illegible Titles", "tags": ["dream liminal", "library", "infinite", "dreamcore"]},
    "096.png": {"title": "The Theater Within the Theater", "tags": ["dream liminal", "theater", "recursive", "dreamcore"]},
    "097.png": {"title": "Golden Hour in the Dead Mall", "tags": ["dream liminal", "dead mall", "golden hour", "dreamcore"]},
    "098.png": {"title": "The Cherry Red Car in the Fog", "tags": ["dream liminal", "beach motel", "fog", "dreamcore"]},
    "099.png": {"title": "The Childhood Backyard Angle", "tags": ["dream liminal", "nostalgia", "backyard", "dreamcore"]},
    "100.png": {"title": "Streetlamps in the Deep Woods", "tags": ["dream liminal", "forest path", "liminal", "dreamcore"]},
    "101.png": {"title": "Empty Bucharest Apartment Block", "tags": ["mundane apocalypse", "apartment block", "summer haze", "liminal"]},
    "102.png": {"title": "The Last Gas Station on the Plain", "tags": ["mundane apocalypse", "gas station", "flat plain", "liminal"]},
    "103.png": {"title": "The Ferris Wheel of Silence", "tags": ["mundane apocalypse", "amusement park", "abandoned", "liminal"]},
    "104.png": {"title": "The Abandoned Sedan at Dawn", "tags": ["mundane apocalypse", "highway", "overpass", "liminal"]},
    "105.png": {"title": "The Moving Swing at Golden Hour", "tags": ["mundane apocalypse", "schoolyard", "swing", "liminal"]},
    "106.png": {"title": "Footprints in the Dust Diner", "tags": ["mundane apocalypse", "diner", "abandoned", "liminal"]},
    "107.png": {"title": "The Calm Rising Tide", "tags": ["mundane apocalypse", "flooded city", "coastal", "liminal"]},
    "108.png": {"title": "The Museum of Hidden Paintings", "tags": ["mundane apocalypse", "museum", "empty", "liminal"]},
    "109.png": {"title": "The Train at the End of the Track", "tags": ["mundane apocalypse", "train", "overgrown", "liminal"]},
    "110.png": {"title": "The Last Lit Window", "tags": ["mundane apocalypse", "high rise", "midnight", "liminal"]},
    "111.png": {"title": "The Wall of Fog Beacon", "tags": ["lighthouse horror", "beacon", "fog wall", "cosmic horror"]},
    "112.png": {"title": "The Glassy Watch of the Keeper", "tags": ["lighthouse horror", "keeper", "silhouette", "cosmic horror"]},
    "113.png": {"title": "Footsteps From Above the Spiral", "tags": ["lighthouse horror", "spiral stair", "ghostly", "cosmic horror"]},
    "114.png": {"title": "Faces in the Storm Waves", "tags": ["lighthouse horror", "storm", "waves", "cosmic horror"]},
    "115.png": {"title": "The Crossing Beams of the Void", "tags": ["lighthouse horror", "twin lighthouses", "void", "cosmic horror"]},
    "116.png": {"title": "The Keeper's Overgrown Garden", "tags": ["lighthouse horror", "cottage", "abandoned", "cosmic horror"]},
    "117.png": {"title": "The Perspective of the Clouds", "tags": ["lighthouse horror", "low angle", "beam", "cosmic horror"]},
}

with open("../images/metadata.json", "w") as f:
    json.dump(metadata, f, indent=2)

print("GOOD Metadata saved to ../images/metadata.json")
